/**
 * ASE Attendance API
 * An API for keeping track of your contacts and the companies they work for.   Don't forget to take it for a spin by clicking on the **Try in Client** button next to each operation! All read operations are public and don't require authentication.  <div> <img src='https://thecontactsapi.apispark.net/v1/img/cropped-contact-img.png' width='90%'> <div>  <!-- ![](https://thecontactsapi.apispark.net/v1/img/cropped-contact-img.png) -->
 *
 * OpenAPI spec version: 1.2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './index';

/**
 * A representation of a Contact.
 */
export interface Group {
    /**
     * Auto-generated primary key field
     */
    id: number;

    /**
     * the maximum students a group can contain
     */
    maxSlots: number;

    /**
     * This property is a reference to registered student for this group
     */
    students?: Array<number>;

}
