# coding: utf-8

"""
    ASE Attendance API

    An API for keeping track of your contacts and the companies they work for.   Don't forget to take it for a spin by clicking on the **Try in Client** button next to each operation! All read operations are public and don't require authentication.  <div> <img src='https://thecontactsapi.apispark.net/v1/img/cropped-contact-img.png' width='90%'> <div>  <!-- ![](https://thecontactsapi.apispark.net/v1/img/cropped-contact-img.png) -->  

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import sys
from setuptools import setup, find_packages

NAME = "swagger-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="ASE Attendance API",
    author_email="",
    url="",
    keywords=["Swagger", "ASE Attendance API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    An API for keeping track of your contacts and the companies they work for.   Don&#39;t forget to take it for a spin by clicking on the **Try in Client** button next to each operation! All read operations are public and don&#39;t require authentication.  &lt;div&gt; &lt;img src&#x3D;&#39;https://thecontactsapi.apispark.net/v1/img/cropped-contact-img.png&#39; width&#x3D;&#39;90%&#39;&gt; &lt;div&gt;  &lt;!-- ![](https://thecontactsapi.apispark.net/v1/img/cropped-contact-img.png) --&gt;  
    """
)
