# coding: utf-8

"""
    ASE Attendance API

    An API for keeping track of your contacts and the companies they work for.   Don't forget to take it for a spin by clicking on the **Try in Client** button next to each operation! All read operations are public and don't require authentication.  <div> <img src='https://thecontactsapi.apispark.net/v1/img/cropped-contact-img.png' width='90%'> <div>  <!-- ![](https://thecontactsapi.apispark.net/v1/img/cropped-contact-img.png) -->  

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.record_api import RecordApi


class TestRecordApi(unittest.TestCase):
    """ RecordApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.record_api.RecordApi()

    def tearDown(self):
        pass

    def test_records_attendanceid_get(self):
        """
        Test case for records_attendanceid_get

        Get specific attendance record
        """
        pass

    def test_records_attendanceid_put(self):
        """
        Test case for records_attendanceid_put

        Update a attendance record
        """
        pass

    def test_records_get(self):
        """
        Test case for records_get

        Get Attendance records
        """
        pass

    def test_records_post(self):
        """
        Test case for records_post

        Add Attendance Record
        """
        pass


if __name__ == '__main__':
    unittest.main()
