# coding: utf-8

"""
    ASE Attendance API

    An API for keeping track of your contacts and the companies they work for.   Don't forget to take it for a spin by clicking on the **Try in Client** button next to each operation! All read operations are public and don't require authentication.  <div> <img src='https://thecontactsapi.apispark.net/v1/img/cropped-contact-img.png' width='90%'> <div>  <!-- ![](https://thecontactsapi.apispark.net/v1/img/cropped-contact-img.png) -->  

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.qr_code import QrCode


class TestQrCode(unittest.TestCase):
    """ QrCode unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQrCode(self):
        """
        Test QrCode
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.qr_code.QrCode()
        pass


if __name__ == '__main__':
    unittest.main()
