# coding: utf-8

"""
    ASE Attendance API

    An API for keeping track of your contacts and the companies they work for.   Don't forget to take it for a spin by clicking on the **Try in Client** button next to each operation! All read operations are public and don't require authentication.  <div> <img src='https://thecontactsapi.apispark.net/v1/img/cropped-contact-img.png' width='90%'> <div>  <!-- ![](https://thecontactsapi.apispark.net/v1/img/cropped-contact-img.png) -->  

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """ DefaultApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.default_api.DefaultApi()

    def tearDown(self):
        pass

    def test_groups_students_get(self):
        """
        Test case for groups_students_get

        Get registered users in any groups
        """
        pass

    def test_records_attendanceid_delete(self):
        """
        Test case for records_attendanceid_delete

        Remove a specific attendane record
        """
        pass

    def test_records_groups_group_id_get(self):
        """
        Test case for records_groups_group_id_get

        Get All records of a group
        """
        pass

    def test_records_qr_student_id_get(self):
        """
        Test case for records_qr_student_id_get

        Get a personalized qr code as base64 string
        """
        pass

    def test_records_students_student_id_get(self):
        """
        Test case for records_students_student_id_get

        Get all records for a student
        """
        pass

    def test_student_logout_delete(self):
        """
        Test case for student_logout_delete

        Logs out the current logged in student session
        """
        pass

    def test_student_register_post(self):
        """
        Test case for student_register_post

        Register a new Student
        """
        pass

    def test_student_register_put(self):
        """
        Test case for student_register_put

        Update a Student
        """
        pass

    def test_student_studentid_qr_get(self):
        """
        Test case for student_studentid_qr_get

        Get the student QR Code
        """
        pass


if __name__ == '__main__':
    unittest.main()
