# coding: utf-8

"""
    ASE Attendance API

    An API for keeping track of your contacts and the companies they work for.   Don't forget to take it for a spin by clicking on the **Try in Client** button next to each operation! All read operations are public and don't require authentication.  <div> <img src='https://thecontactsapi.apispark.net/v1/img/cropped-contact-img.png' width='90%'> <div>  <!-- ![](https://thecontactsapi.apispark.net/v1/img/cropped-contact-img.png) -->  

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.attendance_record import AttendanceRecord
from .models.error import Error
from .models.group import Group
from .models.qr_code import QrCode
from .models.student import Student
from .models.user_data import UserData

# import apis into sdk package
from .apis.default_api import DefaultApi
from .apis.groups_api import GroupsApi
from .apis.record_api import RecordApi
from .apis.student_api import StudentApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
